<a href="https://colab.research.google.com/github/Tawhida222/C-programming/blob/main/Welcome_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset

df = pd.read_csv('/content/heart_failure_prediction.csv')

In [2]:
# Show first 5 rows
print(df.head())

# Dataset shape
print("Shape:", df.shape)

# Data types and non-null values
print(df.info())

# Summary statistics
print(df.describe())

   Age  Gender Chest_Pain_Type  Resting_BP  Cholesterol  Fasting_Blood_Sugar  \
0   69    Male        Atypical         106          250                    1
1   32    Male     Non-anginal         124          396                    1
2   89  Female     Non-anginal         164          256                    1
3   78  Female         Typical         116          297                    1
4   38    Male     Non-anginal          88          386                    1

                    Resting_ECG  Max_Heart_Rate  Exercise_Induced_Angina  \
0         ST-T Wave Abnormality             171                        0
1  Left Ventricular Hypertrophy              73                        0
2  Left Ventricular Hypertrophy             157                        0
3                        Normal             163                        1
4         ST-T Wave Abnormality             123                        1

   Oldpeak        Slope  Num_Major_Vessels        Thalassemia  Diabetes  \
0     0.92         Flat                  2             Normal         1
1     0.92  Downsloping                  2  Reversible Defect         1
2     0.92    Upsloping                  1       Fixed Defect         1
3     0.92         Flat                  1  Reversible Defect         1
4     0.92    Upsloping                  3       Fixed Defect         0

  Smoking_History Alcohol_Consumption Physical_Activity_Level  Family_History  \
0          Former               Heavy                     Low               0
1         Current                 NaN                     Low               0
2          Former                 NaN                     Low               0
3          Former               Heavy                     Low               1
4           Never            Moderate                     Low               1

     BMI  Heart_Failure
0  36.92              1
1  36.92              1
2  36.92              0
3  36.92              0
4  36.92              1
Shape: (10000, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      10000 non-null  int64
 1   Gender                   10000 non-null  object
 2   Chest_Pain_Type          10000 non-null  object
 3   Resting_BP               10000 non-null  int64
 4   Cholesterol              10000 non-null  int64
 5   Fasting_Blood_Sugar      10000 non-null  int64
 6   Resting_ECG              10000 non-null  object
 7   Max_Heart_Rate           10000 non-null  int64
 8   Exercise_Induced_Angina  10000 non-null  int64
 9   Oldpeak                  10000 non-null  float64
 10  Slope                    10000 non-null  object
 11  Num_Major_Vessels        10000 non-null  int64
 12  Thalassemia              10000 non-null  object
 13  Diabetes                 10000 non-null  int64
 14  Smoking_History          10000 non-null  object
 15  Alcohol_Consumption      6650 non-null   object
 16  Physical_Activity_Level  10000 non-null  object
 17  Family_History           10000 non-null  int64
 18  BMI                      10000 non-null  float64
 19  Heart_Failure            10000 non-null  int64
dtypes: float64(2), int64(10), object(8)
memory usage: 1.5+ MB
None
                Age   Resting_BP   Cholesterol  Fasting_Blood_Sugar  \
count  10000.000000  10000.00000  10000.000000         10000.000000
mean      58.584900    139.56920    247.206200             0.505400
std       23.645835     34.86205     86.862739             0.499996
min       18.000000     80.00000    100.000000             0.000000
25%       38.000000    109.00000    171.000000             0.000000
50%       59.000000    140.00000    247.000000             1.000000
75%       79.000000    170.00000    322.000000             1.000000
max       99.000000    199.00000    399.000000             1.000000

       Max_Heart_Rate  Exercise_Induced_Angina       Oldpeak  \
count    10000.000000             10000.000000  1.000000e+04
mean       129.346600                 0.507200  9.200000e-01
std         40.316689                 0.499973  6.250868e-14
min         60.000000                 0.000000  9.200000e-01
25%         95.000000                 0.000000  9.200000e-01
50%        130.000000                 1.000000  9.200000e-01
75%        164.000000                 1.000000  9.200000e-01
max        199.000000                 1.000000  9.200000e-01

       Num_Major_Vessels      Diabetes  Family_History           BMI  \
count       10000.000000  10000.000000    10000.000000  1.000000e+04
mean            1.481400      0.501200        0.506300  3.692000e+01
std             1.117488      0.500024        0.499985  7.176840e-13
min             0.000000      0.000000        0.000000  3.692000e+01
25%             0.000000      0.000000        0.000000  3.692000e+01
50%             1.000000      1.000000        1.000000  3.692000e+01
75%             2.000000      1.000000        1.000000  3.692000e+01
max             3.000000      1.000000        1.000000  3.692000e+01

       Heart_Failure
count   10000.000000
mean        0.503600
std         0.500012
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         1.000000

In [3]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Age                           0
Gender                        0
Chest_Pain_Type               0
Resting_BP                    0
Cholesterol                   0
Fasting_Blood_Sugar           0
Resting_ECG                   0
Max_Heart_Rate                0
Exercise_Induced_Angina       0
Oldpeak                       0
Slope                         0
Num_Major_Vessels             0
Thalassemia                   0
Diabetes                      0
Smoking_History               0
Alcohol_Consumption        3350
Physical_Activity_Level       0
Family_History                0
BMI                           0
Heart_Failure                 0
dtype: int64

In [41]:
df[['Age', 'Gender', 'Chest_Pain_Type', #'Resting_BP',
    'Cholesterol',
       #'Fasting_Blood_Sugar', 'Resting_ECG', 'Max_Heart_Rate',
       'Exercise_Induced_Angina', #'Oldpeak', 'Slope', 'Num_Major_Vessels',
       'Thalassemia', 'Diabetes', 'Smoking_History', #'Alcohol_Consumption',
        #'Physical_Activity_Level', #'Family_History', 'BMI',
    'Heart_Failure']
      ]

,Age,Gender,Chest_Pain_Type,Cholesterol,Exercise_Induced_Angina,Thalassemia,Diabetes,Smoking_History,Heart_Failure
0,69,Male,Atypical,250,0,Normal,1,Former,1
1,32,Male,Non-anginal,396,0,Reversible Defect,1,Current,1
2,89,Female,Non-anginal,256,0,Fixed Defect,1,Former,0
3,78,Female,Typical,297,1,Reversible Defect,1,Former,0
4,38,Male,Non-anginal,386,1,Fixed Defect,0,Never,1
...,...,...,...,...,...,...,...,...,...
9995,49,Female,Asymptomatic,280,0,Fixed Defect,1,Former,0
9996,39,Male,Atypical,249,0,Normal,1,Never,1
9997,72,Male,Non-anginal,181,1,Normal,1,Former,0
9998,74,Male,Non-anginal,109,0,Normal,0,Never,0
9999,30,Male,Atypical,379,0,Normal,1,Current,0

In [48]:
df_cleaned=df.dropna()
df=df_cleaned.head()

In [49]:
df.shape

(5, 10)